[view_keys]

[spend_keys]

[payment_addrs]

[keys]
basala = "encrypted:d2c905d0204c4e75f4a9524e837ac813de4743e0fcb0902455c1617094deaa9b95e70becdbdc25ca2c4fe2ab759bd25edb3ef9da4cbb8cfaceff9cf0bdfe6314a7d6f2088167ed90e6add0682775fa81d3ee1bb02c6fc1503d"
basala-consensus-key = "encrypted:aabd8f45ebc19e45bad0bd1522e9f1dd3d5181c1abdfcaf928296141c9e06f7d05b75bdfa2904a35c7c9abeff6fc59c7533c577283fc4cb8aac46e15d5d4f37df2ad771c085f4a1259db5917fd74b24fba7365f3508ff01d33"
basala-key = "encrypted:03ae50b60c7a5c02df24bcf2849ca66c51a60cd9abeccab2771abd2759b8f6633352085991ba6194c29ada1b074da95790ca4774b7f99a22df7d1d50a00a14d4ebdde0e4bc5242123f55ffa8dae196e01db00e35e1f4dcb927"

[addresses]
jakeperalta = "atest1v4ehgw36xye5gwphxap5vdphgdq5yv3cg3p5gdf4gerrqdesxycn2de4gc6y23j98y65vs3j83u34h"
fego = "atest1v4ehgw36xdzy2se4gepygvehx56rxdfkxccnj3fjxveyyvp3x3prqw2ygerrz3pk8ycrsdpnpk23w5"
croutondigital = "atest1v4ehgw368qerzvfkgverzdfe8q65vvjrxapngsj9xuursv2z8qurz3pkxgc5yvesxdz5vdehh3q9xk"
blockval = "atest1v4ehgw368q65zwz98yc52v2rxumrysejgfzrv3jrxeryzwp5x3ry2v2xg9znwvp58qmnwv293ye368"
andfat = "atest1v4ehgw36gcungv3sxapnzd698qeyxvfng5enwsf3xdrryw2xgscnysekxuurv33ex5mngsenfs73wx"
"lavender.five_nodes" = "atest1v4ehgw36gv65xdfngcey2wzyxg6nydp5x5enydpn8pqnss6pxc65vwp3xvmygs6x8q65ydpjh9ljqc"
stake-take = "atest1v4ehgw36gycnxvp5gguyvdzxxqmrg3zzxyurwvfsxuur2dfkxvcrjd29x3prys33gyerssehtza5vl"
lapatylin = "atest1v4ehgw36gezrgvjrxpryzvfkxfznsdj9xuey2vz989ry2wph89rrzs2rxumygs29xvcnwsfn0dd37s"
amadison79 = "atest1v4ehgw36x4ryg3zrxqcnq3fjxvmrzsfc8prry33kgg652sf5gcmrw3p58ymnzve4g3p5yv3n2nxgre"
cupid = "atest1v4ehgw36xvmyzvz9xym5z33eg3ryyvfexaq5ywfsxazngdj98qmrjdzz8ppnxwfk8qc5vd3evqxhwx"
anonstake = "atest1v4ehgw36x4q5vwf4g4zrjv2rgfzrzwf4g56y2v3ng3pyydzzx4qnwsfhx9zyxvfjxdprysfj67crxl"
bvs = "atest1v4ehgw36gdq5xd6yxgurv3fhxpprzse48qcr2secg3zrxv6r8pznzv6yxvmngv3eg5mnxd3ky0s20h"
staketarget = "atest1v4ehgw36xsc5xvecxuuyy3f4xcm5vd2px5u5vsf38yerw3fngs65yvfhxez5xwz98qe52vzy32cthu"
alkadeta = "atest1v4ehgw368pqnzs6xx4znx329xym5gd3cgcmnsdpeg3p5zdpc8qmn2wzrgfzyydpjgsungv3he7as2z"
binary_holdings = "atest1v4ehgw36gezy2wfhxpp5xdp4ggu5vv6z8ymrvs3hx5urz33jg5e5xwpsxycrywp3gvun2dj97d8mpg"
pos_slash_pool = "atest1v9hx7w362pex7mmxyphkvgznw3skkefq2dkxzumgypgx7mmvyqszqgpqyqszqgpqyqszqgpqecxumt"
nodersteam = "atest1v4ehgw36xucnzd6rgyerj3f4xscrvvpjx4q52s3ng3ry23fex5uygvec89rygs6xgsc52dj9wqdq90"
awa = "atest1v4ehgw36x3zyvdfhxeq5vdeex5enw3fcgeznjwfjg4q5ysenxdqnxdp4xcm5ys35x3rrxs2ymu2mfz"
welldonestake = "atest1v4ehgw368q6nxd3egscngwpjxcersvp4g9p5z3jxggungv33xuer232xxpzrss3nxucr2d2pt86qxy"
ptzruslan = "atest1v4ehgw36xcm5vdzrxcen23p4xseyy3zyg3qnjd6rx4prydfc89pns3jpgvunj3pkgvcr2wzr7nazsy"
node_guardians = "atest1v4ehgw368ppnjd3h8qmrsd2rx4pnvwzrxsu5ywf4x5crwvz9xg6nwwpcgymnww2zg4qnw33cvwhtyv"
"staker space" = "atest1v4ehgw36g5crjwzxg9qn2s3sgsunzwzyxqmrvvz9xcmyv3p5xg6r2d2ygcmy2v3cxpprgw290292kk"
hedji = "atest1v4ehgw368qenwd6xxyuyvvps8q65gsecx3z5gv6zxucrxdehg3qnjdesgfq5yd3jxseyxs6pdu38uz"
web34ever = "atest1v4ehgw36xucyz3jxxpq5gd69xqunyvpj8ymnydjpxycrydesxuunqd6p8y65gdf3xg6yydjr8dktpn"
wetez = "atest1v4ehgw36g9z5vvfnxguyyd3ex5crq3fhgcuyvvjxxuun2v33xq6ng3jrgym5xd34gyer23f4p8wanl"
gnosed = "atest1v4ehgw36xgenqve3x56ry3f5xqmngv3n89qnwsjxx4rrzwfcggc5xvpkgerry3pcgg6nvsectxzmxx"
oneplus = "atest1v4ehgw36g5mnss6z8qurswfjxuunws3hggc5xv3jxqcyysfh8qurgsjzxcur2wpcxumn2ve3l0r5cc"
zssbecker = "atest1v4ehgw36xuungv2xxcmy232xx5erv3fjx5ursvzrx5uryd35xyerxvpkxaqnsw298yunydp3njl892"
konsortech = "atest1v4ehgw368y6nw3358qcngv3sxgeyvv3cgcmryd3hxserwv3kgce5vv298qmrxvpkxqcrvdzrspgs6p"
alxvoy = "atest1v4ehgw36gycr2vfngyc52wp3x9p5y3pjxqun2wfjxdzngw2px5crws3sgvcrq33nx3pn2d35ecet96"
nocturnallabs = "atest1v4ehgw36g5ens3f3gc65vwfnxdqnj33sgdp52v6z8qurqwfkgycyxv2pxfp5ywzy89qnydphyn4t0x"
genesis_lab = "atest1v4ehgw36xguyzvzygymyyv6rx4prwvjzxu65gs2rxqurgw2pgs6rzsf4xuerzd698pq5vwzxcph480"
apepperony = "atest1v4ehgw36xppnjwzxgsurywfcxfpn2w2rxgcn2veng9qnzdp5xy65zd2rxppy2seexfpy233n7j4dug"
furkan = "atest1v4ehgw36xvmn2secxs65y33kxpq5zsj9xaq5zvesxdpyydfcg4p5xvfnxaryxwf58yen2sesurmx8c"
5elementsnodes = "atest1v4ehgw36gyervv3sgse5x334geqnjs34xvcnxv6zgv6rjvj9xezyxsf5xv65xvpj8pprswfc2jx7fh"
forbole = "atest1v4ehgw36xyer23psgg6y2dekxgmryd6xxppyg3p5ggunw3zzxppnww2y8yenjv3h8qmrgv3s20mc66"
888tnso = "atest1v4ehgw36gsc5x33hx9zrxv29g5enqvp3gcmr2wfcg4p5zd33gc6rvv2yxpznzwpjxsey23zr5d6cvs"
lefey = "atest1v4ehgw36g5unws6zgfpr2s3ngyunwd2yxepyyvpcgez5vd33xum523fkgsenzvengdrrzvjzlp0nql"
dsrv = "atest1v4ehgw36gyeygs3c8pzrywzxxaprwvp5gc6nq335gscnvdzpx4zr2dz98q6nwvjrxdpyxv6y8nppvt"
lemniscap = "atest1v4ehgw36xycrjvjrxvurvve3xccrqvenxuerxve4gge5zdjzxyunys2ygg6nwvfh8yc5v33nl4rtjl"
mdlog = "atest1v4ehgw36g56rj3jxxdz52v3kgv6yvsfh8pqngsecx3qnsvejxaz5gwpjxyengwpcg565gdfnrumkqw"
eth_bridge = "atest1v9hx7w36g42ysgzzwf5kgem9ypqkgerjv4ehxgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq8f99ew"
01node = "atest1v4ehgw36gcer2vfkxez52sjpxfrryd3egezrwdzpgvcy2s35gvcrz3zy8qervs6pxu6rxs2xcxpart"
figment = "atest1v4ehgw36gv65xvenxdznx3p58qunwv3nxcc5ywzxx3z5y3fjxucnywp3gsergd3nggcyy33jpwenus"
enigma = "atest1v4ehgw36g4rrsv2rxgunjdzrxccrjd3jxycnsdjpgcmy2dzrgvcnw3zy8yuyzd2zxpzyv3fcjxa248"
trdm = "atest1v4ehgw36xucnzd6rxep52denxquyzs2yxg65gsjzxeznssf4xcuyxd3sxpznzwp3gvcy2vehv8fcgp"
kartoffel = "atest1v4ehgw36gep5ysecxq6nyv3jg3zygv3e89qn2vp48pryxsf4xpznvve5gvmy23fs89pryvf5a6ht90"
onfly = "atest1v4ehgw36xuurjwf5gfpr2d2zgyu5xd34g4prxdjzgeqnvseex4qnysjzxez5zs2zgg6yy33cq5kpu3"
pucha = "atest1v4ehgw36gyunvd6rx56yvdpcx3pnyvzpxpqnswfsxapyzw2yxaqnqw2rggey2v29g9zygwpk6gwhdc"
pos = "atest1v9hx7w362pex7mmxyphkvgznw3skkefqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqq8ylv7"
viknov = "atest1v4ehgw36gvmyzdjzxscy2wf5x5cyvv29gfrrj3jzxvcnyd2xx4pnss6z8qun233jxv6nysf4tl8xx7"
scania = "atest1v4ehgw36xpp5yd3cgsmnvdeeg5u5xvehxppygvz9g3z5xwfjxcen2wpexgc5xsjpggmryv3clxwyav"
testnetrun = "atest1v4ehgw36x3p5vd3hgvmnydpexyersw29gc6ngv3jggunwwfnxcen2vzzggcnvvfhxquyy3fcnxa72q"
stakecito = "atest1v4ehgw36xeprwdf3xucngs34gerrjvfkgfznvv3j8yu5yv6x89prjw29gccyzwzpgvun23p5zrcgfz"
blockstake = "atest1v4ehgw36xvuyzs6yx56rxsecxucrxsfexgmrzs3exdznzses8q65yv6zgfzrgvfk8pryyvpk7rcxv7"
cyberg = "atest1v4ehgw36xvmrvwphgye5xw2xxsu5zvphgc6ng32zxve5gsesgerrys2zxprrjs2rgepnqveh0whj5e"
huginn = "atest1v4ehgw36xfzny3psgfqnxv2rxsmr2sjp8qm5ys3jxger2wzyxvcyxdeexcu5y3jzgcerzdj9qgp99t"
roadz = "atest1v4ehgw36xyeyxvpjx4rrzd33g5eyv3fsgymrjsjp89pyxdfs8qurs3pk8q6ry33sxfz5ywzpwu57gd"
bondedzone = "atest1v4ehgw36xvenwdj9g3zrwsfhxsm5xd6rgs6rxs3egg6ngwp4gdqny3phxguyzvzyx9qnqvz9m2hrar"
zkv = "atest1v4ehgw36x5crxvpnxv6nsvengse5g3j9xc6nyd2xgse5vsejgymrs3fc8qu5vw2pgepnyvpkt4380k"
chainflow = "atest1v4ehgw36xgmnwdzyx5cnzdekxveyzv6pxq6rw3fsxq6rgwfjx4pr2se4gycygvfegc6rxvf39ur3y3"
stakingfacilities = "atest1v4ehgw36xg6n2vfkxppryvjyx5uy23jzgcerzdp5x4z5ywp5xg6rvv2zgdzrw33jxqur2d3hqnph0c"
"newton.zone" = "atest1v4ehgw36xepnyv33xseyy3jy8y6nzw2pxdrrjdzpxdp5v32rgyc5zdfh8yeyyvfhgv6rgd6p4tq0gw"
jascai = "atest1v4ehgw36g9z52deng4znydpkxc6n2s6xxverqve3g4rry3jzgcc5g3p3xgm5zd2xxu65y333cjne65"
jglp = "atest1v4ehgw36x3zrs33egfz5gwf38qunqsjxgeqnwv6rx3rrvse4g4qnqs2xgyerzv69x5mrsvpskgxf8v"
zerokcap = "atest1v4ehgw3689ryzwpcg3prz3psxycrws3egs6nvses8qersvzrg4pyxvf48pz5ydjpgc6nw3jr9rur6y"
basala-consensus-key = "atest1d9khqw36x4z5gs6xxpzngv3sgsurywpjx9zyxsfsgc6nz3fjgeprjvzr8ycrx3fnxycnzsfktwcw2m"
apfel = "atest1v4ehgw36gfryydj9g3p5zv3kg9znyd358ycnzsfcggc5gvecgc6ygs2rxv6ry3zpg4zrwdfeumqcz9"
wallach = "atest1v4ehgw36x9qnxwzrx9pnxsf5x9rrvd3eg5cr2sejxgenzvjx8pp52sesx9zry3phg5e5v3zy3j5x7p"
"cryptosj.net" = "atest1v4ehgw368q6rvsf4x3prysengycn2d6rxarygsjpxsc5xsfjx9rygvzrxcurvwfnxgc5yv3k3cvhf6"
terlia = "atest1v4ehgw36xymrx3pjg3zngwzrg56n23p5gv6njvekg5mrjdjzg56nqs3jxuunv333gyurqdzx5j0xxt"
irvo = "atest1v4ehgw3689zrj3jyxezyxwf4xqmrysjrxvcngw29x5m52vjzxcc5gdf48ymnj3p3xpryvwf3h0x3gh"
robin_bobin = "atest1v4ehgw36xppnwv69x9pnzdfsgymyzs3sgccrw334g3znqwfhx9py23phxy6yxdp5gycrzs3cgt2gd4"
saltfish = "atest1v4ehgw36gvunydekxqeyvd34gerrs33sg4zrsdejxarrzvjpx9py2w2yggm5zvf5xpz52wzpyryn6h"
basala = "atest1v4ehgw36x9p5z3jygyuryw2zgverzwfsg9pnzwfngvm5vde4xfp5yvf4xuunq3p5xceyzsend8yxyz"
polkachu = "atest1v4ehgw36xfzng3fc8pqngsf5xsmyxwfcg5ung334xccy23fkxyungvfjxfrrjwp3xucyxv3cmandle"
vinjan = "atest1v4ehgw36gcungw2p8qcrvd3kxvunsw2pgyeyzs6xxqu5x3p58yurxd6zxs65yvpjgeq5gw29sfyllh"
simply = "atest1v4ehgw36xppnzs3jxazyxd2xgfq52sesxvurzv2pg4prx3fhxy6rgvejgez5zsjpg9znsde59e3kyp"
memas = "atest1v4ehgw36g3zr2vejgepyywzzgscr2wp4x3zygdpc8pzngd2rgse5gdf3xyenzs2pgy6rxdp5cujchl"
openbitlab = "atest1v4ehgw36xdqnjvjxg3ryz3pkxuu5gve5gc6n2d2yxqc5vd6yxprrsvfsg5mrzv348pqns3pepavf0p"
foosball-validator = "atest1v4ehgw36x9prv333xfznswpegyerjsfcxpp5z3pj8ymn2vzpxqunys3exgeyvsfnxccrjwp3mzujxc"
vidi = "atest1v4ehgw36gyenss6zgvmyvv6zxarrzv2z8ym52vfnxye5ydz9ggcrxve4gyurws35gep5zvjrz73ddm"
kelpie = "atest1v4ehgw36xyenwsfnxgunyd6zx9zrsd3hxfz5zsfkgsurq3zxggmrjdp5gccrgd35xaryzd6996rr0l"
everstake = "atest1v4ehgw36x4znwsf3g9qnzs2xx56rzvf4g5cn2wzrgeqnywzyg56rx3p4gyenw3pnxgmrgs2rz5vynf"
bwarelabs = "atest1v4ehgw36gycyzvzz8pzn2d3jxg6nvs69xc6r233cxgcyxvjxxpqnzdj9gvmy2vphggunwsfsdn5hj4"
owlstake = "atest1v4ehgw36g4pnwdzzgcuy2s2yg9zrvsecgvcny3fh8qcrxv34gvmrsve3xpq5z335gymrjv347836lh"
crypton = "atest1v4ehgw36gsunqvesgeqngwphxv6nx33nxs65yv33x5unqs3kxgeygdpjxqc5232rg3zngdzp8kry2a"
geonodes = "atest1v4ehgw3689prv3fsx5crx3fnxsury3fsgerrxd3e8pp5gd35g5eygde4xvu5y3z9xu6nwvp3h0825d"
encipher = "atest1v4ehgw3689zyyw2rxdzrws6rggurqw29ggenjw2rg5cnvs2rg4zrwdp4xapryvfnxfznssjpgak7fd"
crypto_universe = "atest1v4ehgw36gsengs6rgguyyvpc8ycygde5g4qnxdj9gezn23pkxpq5gd6rgdprywzxx5mnjseh7zgzsd"
masp = "atest1v4ehgw36xaryysfsx5unvve4g5my2vjz89p52sjxxgenzd348yuyyv3hg3pnjs35g5unvde4ca36y5"
cryptobtcbuyer = "atest1v4ehgw36gcmnjvjrxppyvsjxgdrrvsecg9znyd2yxsunjvjxx4rrsd34xv6nq33cxgunsv3kfz4nx4"
supimba = "atest1v4ehgw36xs6yx3f4x5mygvfexdznzde58ppn2vp4xsenqd6yxvcr23pcgy6ryde5x3qnx32yle86xy"
galaxynode = "atest1v4ehgw36xuurq3fsgc65gvp5xeprgdp5g4rrwveh8qcnjs33xcmrz3pkxdzrvdzxxuerg33e3spmu3"
blockonaut = "atest1v4ehgw36xs6ryvphgsm5zdzpgvunvd34xeprxs6rgfznwd6pxucyzdzzggcrzv3kggmyysjr06vsuc"
orahapris = "atest1v4ehgw36xycnvwf4gdp5z3jxgcungs2rxce5g3jp8yu5vs2yxdznqwzrg9rrsdzzgezn2djxhqyfr7"
p2p-org = "atest1v4ehgw36xqerxde4x3qnxd6zxpry2wfjx5erqwzrxucnwvecgsunzsjyx9pnv3p4xery2sf4dpstfu"
mandragora = "atest1v4ehgw36x3pnjvjy8qcnvd35xqcnvwpk89z5gv2xgvunssen8yenj3zzgyc5vseng3z52vf55qgdy0"
dot = "atest1v4ehgw36gg6nvs2zgfpyxsfjgc65yv6pxy6nwwfsxgungdzrggeyzv35gveyxsjyxymyz335hur2jn"
serana = "atest1v4ehgw36g9znjsfhg9z5vdehxazyydpng4zns32p8qe5ysehg3pnxve38pp5zvejxcmnqsee4xusz3"
jetrix = "atest1v4ehgw36xprrvw2rg5mnvdjrgfprgd6xxep5xwfnx9pnv3jpxumyy334gdryg3jpxarrxdfk9k2mdf"
peach = "atest1v4ehgw36gcmnwv3j8ycnxvjy8ycryv6xxquygvekg4p5ysfeg5unvs3jx56rswpsg56yvv3enfme5h"
tdrsys = "atest1v4ehgw36gdzyyw29xerrvs2xg9p5233jx4ryydpsgeqnvs3cxdrrqdjpgdprgwpk8qmyy3pc6v552p"
adrian = "atest1v4ehgw36g5crv3fexppnwdpsxvm5xs6xx5cnxdfngg6rq3pjx5unxd6ygep5v3z9xuurgdejlf2lkd"
itrocket = "atest1v4ehgw36xqmngvjygccrzd6zxyenyd34xpp5xdehx3z5xd2rxvmrj3zxx5crys6rxyeyvdphj5d8vd"
brightlystake = "atest1v4ehgw36xppyzd35gdznvdenxprrswf5xyuy2dj9xyurvwfhxppnw3p4gverjdzyxccngsjrrn7lz4"
wave = "atest1v4ehgw36g4pnqs35xaq5g3fcgezrvdzxxquyxsjzxymrjwp38ycrxs69x3rrxw29x4znqvf3ymr8mc"
perfect = "atest1v4ehgw36xpprxwfjxy65y3zp8y6ygv2xgscnss6yx4zrs32zxqcny3z9xvenvwfhxce5x329deqtvx"
n1stake = "atest1v4ehgw368yurss6yxccnjdp4gfryzs29x5cnvd3jgc6rx3fsg5cnxvpsx5mnsdfkgfz5gdenhlacng"
tacodan = "atest1v4ehgw36g3zyvdjpxy6yyd3cg5eyzd2pgge5xvjyxyunxdjyxgurxwphxqmrvsfkgymrsw2yp5hele"
jasondavies = "atest1v4ehgw36x3zn2v6rxgeyv3f58yuyzv34xye5z3zrg9pn2d2rg9ryg3fhgy65z333gsenvv3n8cvq7j"
ppnv = "atest1v4ehgw368yerqs6zxveryvzrxverzwpkxc6n23p5x5crxwfkgsmrzw2xx3prgd6pg5cnxvpk44x559"
weakhand = "atest1v4ehgw36gserzdfexccy2w2rxsu5zs3sg5enxdejxprrsdjzx5cr2sf4xq6yvd6rxcmnss6xvc0gyp"
stephenye = "atest1v4ehgw36xsenydz9g4zyzdp3g9znwvfj89prqdpkxy6yzdej89pnjvpegv6nzdjr8q6yywfj38jkch"
o2stake = "atest1v4ehgw36xcmrvs6yxaq5gd35g3ry2secgfqnjveexscnjv2zx3zyzdpexu6nxsfjxcuyxvpk4rkehg"
sevani = "atest1v4ehgw36xaprzvp4xgerz3pjg4qnsde4gezyydjzgdz5zs2yxfpng3fnxgmyzdphg5m5y3p30h3j32"
tothemars = "atest1v4ehgw368pzrxwpcxeq5z3png4q5zv2zxpznq3jrxqurgvjpxcmrzs6r8ymn2d33xpp5ys2r07l2gq"
nodeaddict = "atest1v4ehgw36gfpngde4x56rys33xazrvdfcxycyysfhxary2wf4gcenqv6ygvmrxdf5xcunzd69p5lvkr"
goldmen = "atest1v4ehgw36xsmr23fexgurwve4xeryy3feg9pnjd29xeprydjz8qc52v338ycrjd2pxc6ngsf5f7kxlg"
knowable = "atest1v4ehgw368qcnvv29x5unsdzp8qmygs35gsm5ydzzgfz52vpjx5uy2sfe8qmnvsj9xge5gd29ltt92j"
swiss-staking = "atest1v4ehgw36xqcyzd2xgfprjs2xxqmnvwp5xqmnxvfsxuunjwp5gc6rys2xggcn2vf3gcm5gdejtvep7m"
ray = "atest1v4ehgw36gymyx3zrxq6rqsf48pp5zvf5g4z5gvzzxqunvdpsgccygsec8qenjdzygvenzse5yl54sl"
stakefish-testnet = "atest1v4ehgw368qunjvzxx4prxs3jg9zrz3fc8qcnjd2yg4zny3zzxg65y3jxxdpnqv35xyerqse5h9daf5"
eth = "atest1v4ehgw36xqmr2d3nx3ryvd2xxgmrq33j8qcns33sxezrgv6zxdzrydjrxveygd2yxumrsdpsf9jc2p"
banderoswall = "atest1v4ehgw36xfznjvfegdzrjs34gycnqdesx9pygwzygdrrzdfexcuy2dphx5enwvfsxqu5yd297s686n"
"stakemake.pro" = "atest1v4ehgw36xu6nqwfjx5urg32xxc6rsv35g3pnxwf5g5m5yse4xaprjs6xxccrx3psxccyyvz9dh3sew"
airgap = "atest1v4ehgw36xvu5xv6px4znwvjxx4znxv6pgsm5gd35xu6nq3zp8pryvv3c8y6r23pcxserxd3ene57pl"
cms-rare = "atest1v4ehgw36gc65zvpcx4p5zwpsxepnyvzpxpprjv6ygvunsdehgg6njveng5uy23p4gymnqvzyg4ns9l"
mtnode = "atest1v4ehgw36xuenqdjz8y6yzw2rx4rrwd69x9rr2d6rx5mrjvec8qe5y3zr89ryyv6px5ungsfj2wvx7y"
rozas = "atest1v4ehgw36xse523p3gsmnx3jrgycyvd3cgg6nsv2r89rygsjyxdzrzd6z8q6nzd3jx5e52d295vcfs8"
linamr = "atest1v4ehgw36xgcrgwpjgycrgwpex3z5v32r89p52sekgv6rw3zyxcmr2sjrgccnws2xg9qngdfhj8epjl"
onthepluto = "atest1v4ehgw36gv6ngv3hg56r2329xym5xw2pxuenw3j98pprw3psxumrq329xse5xd6pxfz5ys2rm28nmg"
rch = "atest1v4ehgw36g9pnxv33g9pnwdpjg4pygdehxgc5z3fjxucy2veexqurwv69xse5y3jr8pz52sfhmfeejq"
nodesguru = "atest1v4ehgw36xdpyz3zyxqcn2wfnx4rr2sjpg9q523zyxyurv3fcgeryx3p5xdrrysjzxqungdeklsp995"
schnitzel = "atest1v4ehgw36xue5xvf5xvuyzvpjx5un2v3k8qeyvd3cxdqns32p89rrxd6xx9zngvpegccnzs699rdnnt"
"nodepro.xyz" = "atest1v4ehgw36x4qnysjpg4qnwsfsgdznvvzxgcmy2d33gdpyxvpegfpnssehg4p5vsengy652dzp53tpfw"
testnetpride = "atest1v4ehgw36gsenvvjzx3zrvd69gfqngdjyxfpnwvf5gsm5xdjyxy6ry334xuunqd2xx3pnjdjz0jhh05"
cb-validator = "atest1v4ehgw36x3zyzvfkgfpyx33hgvmn2wpj8q652wfexsmrjsekg3pnzv3kgdrr2dfjg9rrzvzrlnh8me"
stakepool = "atest1v4ehgw36xgm5zd3sx5eyzd6rx5mnjdpkxqcng3fsggunwdjpxquyydpe8qenwd3eg9znv33jpry0e5"
liveraven = "atest1v4ehgw36xum5gd35xcc5zv2pggeygsej8ppng3zp8qe5gv2xg9rrvv2zgdrrqdenxu6nysfjwxtgey"
chorusone = "atest1v4ehgw36xcenydfcxdp5gs3hgvc5x3zzx3p5xdjy8pry2des8pp5ys6pgg65y3jyxaznqs2rn48th4"
nkbblocks = "atest1v4ehgw36g56nydp38qcnswfhxuc5ys298qenqwpk89pnjdz9xcu5vd3h8ymrsdjrxsunvwf3qnp6zs"
fairstaking = "atest1v4ehgw36xfpnq3p4xqenyv3kg9rrwvee8qensdfexy6rvs69x4pyzsfkgsm5gdecg4pnzd3jmedcjj"
web3addicted = "atest1v4ehgw36gv6ngde4xdprxs6pxg6rw333xccyy3fcgc6ngdzz8q6rxs3jgcenx3fkgceyz32zwnys8y"
ern_ventures = "atest1v4ehgw36x4z5zvp48qcrw3jzxven2sjrxs6r2sekg5cyyvjzxaz5yvfsggcrzwzrgvcnzvzp3fffkw"
razil = "atest1v4ehgw36xqm52venxueyzd6rgycr2dpn8qcnqse3gfznxwfnxcuyxd3egs65vs2pgfzyywp5avvsgt"
btc = "atest1v4ehgw36xdzryve5gsc52veeg5cnsv2yx5eygvp38qcrvd29xy6rys6p8yc5xvp4xfpy2v694wgwcp"
sbb = "atest1v4ehgw36ggenjwfs8qcyxvz9gy6rs3psxazyywf5gvcrq33ngdz5xdp4xfznv3f3xu6rqd6zfxkcle"
dokiacapital = "atest1v4ehgw36xceng3pcxpqnzd3e8yerjve4gveyg32rgep5xd2xgdprvse489z5vvfhx3rrs33shvk77y"
campbell = "atest1v4ehgw368ycrzvpeg56ygvpkxv65v334x4ryzwphgcc5vdfjg4ryg3p4gdpngv2yxqu523jy6mulmz"
blackblocks = "atest1v4ehgw3689pyz3jzxvc5xd2pxcungdf3gdqnxs2pxcuyxvp4gvmnyd6pgveyz3p3xv65gdpkzzp8s4"
mounir_node = "atest1v4ehgw36gez5g33s8qengsjrxg65x3fjx4znxsfjg5erxvecx3zn2wpeg3znxwp3xg6yyvp4zv2ggl"
kryz = "atest1v4ehgw36ggenjsej8qenssf4xgmyvv3nx5crxvf389zyzvf3xsunqvfsxfzngwzz8y65zvpc6nwch7"
aleennado = "atest1v4ehgw36ggcrvsej89zyxvz9x3qnywpng565ydj9xueyzsfngycnsw29xezyyw2rgfz5xsf3pq74es"
stakeup = "atest1v4ehgw36xuurgdfnxquryvfegscryv35xu6n2vp4xfq5vs35xqcyx3psx4prjw2rgvu523pkryx92a"
namadaworld = "atest1v4ehgw36xfpnvs698q6yzwzpxgcygw2zx5myvs33gyurgd2xxvcnys6rgcery3f389zyx3p5a3svlj"
informal-systems = "atest1v4ehgw36gscnqseexqcrwvp3xvengvesgycrv3z9xfpyzdjyg3pn2vpsxym5vsjzg4qnq3zzc8njg6"
2pilot = "atest1v4ehgw36xaprss69xcuyysfhgs6rgv2r89pngv6zgccrxs2yxdzn2dpegdrygvfnxum5vvzpyqhw7e"
nakoturk = "atest1v4ehgw36xaprvwpcggcr2wpjgseyvv3egyunjwfjx5mrjdzygdpngdfcgezrzvzpgfpnwdf5rrym56"
azstake = "atest1v4ehgw36ggmyzwf3xqm5gwpcgserwse3g56rjdjrxfpnqvfeggergsj9x9zry3fsxeqnyvj9jezged"
faucet = "atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3"
maragung = "atest1v4ehgw36gc6rwd3cx56rzdenx9rrv3fcxumnzsfnxscnvsf3xfznx3p4xfqnsvpkxaz5gw2zw3s0lu"
b-harvest = "atest1v4ehgw36x5urzdfngvm52dzxgsu5gveexaqngs3exvmnvvejg56rvs3hxv6ygvjzgsurw3pcgshx40"
firo = "atest1v4ehgw36g4z5y3f5xucnsdfngsmnsvejgce5vdpe8yc5vvzxx9ryvvesx4pnvvfsxpq5yvenwqpjtk"
bengt = "atest1v4ehgw36gvu5xve3xeqnjdehxpqnsdeexfp5ysehg5mrvdenxarrss69xscygvz9xqeryvpn230kuq"
basala-key = "atest1d9khqw36gcmnjdehxsmrwdpnx9pyxveegserwvz98yc5vwzxgdryvs34gfp5vvpnxqu5gve3e6hf92"
uniqlabs = "atest1v4ehgw36xum5zdpnx9prgd3sgy6yvdzyxazrvd29g3pnxvfkxumyyvpcxaz5v3j98prrwdpk8w462e"
conqueror = "atest1v4ehgw368yc5gvzzxfzr2sekxycnvs3kg56yxv3jxeqnqd34xqcn2vfkxcmyvs35xqurs3p5dtgju0"
1ce = "atest1v4ehgw36xyengvzyx9znz3phx5erjdzxgfz5yvfhg9z52v29x4p523zrgdzrwdzz89rrxdejfee7gj"
illuminati = "atest1v4ehgw36xsung3f48q6yy3pcxqm5vde5gezrq3fexgcrydjrxumrqdpexgergdpngfzyyv3njm8n5g"
coverlet = "atest1v4ehgw36x4zrsv6yxvmrwse3gvcrzwf5xsurssfsx4zrydpsg9znjwpexyenjv35gezrjd6zp4mygd"
hashquark = "atest1v4ehgw36x4p5y3pnxcu5gdfsxfp5gsfnxfp52vfe89ryywf4xgmyyv3exfpn233exc6nv32xdgcecl"
nam = "atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5"
sandman = "atest1v4ehgw36ggerq33hgccrxve4gv6yys2pxdzrgd33g5uyyvfkxguyxv3hgsenyvzzxqmnqvp5smcavv"
governance = "atest1v9hx7w36gahhvetjdeskucm9yqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq5a20qt"
gian = "atest1v4ehgw36gy6ngv3cx9q5xvp3xqcyzvekgy6rsv6zgs6ng3fjxuerwv2xxyunzv33g4prxsjpprp0fc"
nodemeister = "atest1v4ehgw36xep5y3fhxdqnvv34x5u5z32z8q6rw33cxcerqs2zxcunvsfjxapr2v34ggurzv3je4zds5"
coinstamp = "atest1v4ehgw36xvurzs3j8qcyzseeg3zns32zg4qnsd6z8ppyy33exq6y2d2xxeznzdeegyenyvzxhgsjpr"
zanshindojo = "atest1v4ehgw36gc6nvsekggmyvs2pgg6nv3pkg3prxsfjg9pnzdj9gg6rw3fjgfznjse5g3prqd3n9cex4f"
validatrium = "atest1v4ehgw36ggu5zdpex4pygwp5xceyyd3h89pyyv3489zrgdpjx5mnwv6xgyen2dfng3ryvdfstzdj2u"
moodman = "atest1v4ehgw36ggm52w2rgyunjs2pxv6nwsfcgcer2vpegepyyde4gscry3p4x5eyxs3exuer2wz9nk2euy"
cosmostation = "atest1v4ehgw36x3prywf3xazrjdeng56n2djy8qunjsehg3prsdfnxarygdp5gdznwd33x5urj32xh05ekt"

[pkhs]
5EDCF0E420D82821DCA0F51E2FB90C903E3111A6 = "basala-consensus-key"
06E5C69BB207D9C2654EA673FC5AF27B1530A9A0 = "basala"
F7977467431BC39D270E91F8FCFFB5BCF0309D31 = "basala-key"

[validator_data]
address = "atest1v4ehgw36x9p5z3jygyuryw2zgverzwfsg9pnzwfngvm5vde4xfp5yvf4xuunq3p5xceyzsend8yxyz"

[validator_data.keys]
protocol_keypair = "ED25519_SK_PREFIX000344d57d00f4504e63c7c747928f2487716e16a3bb7c8fb067fb495f8322b146"

[validator_data.keys.dkg_keypair]
decryption_key = [36, 108, 97, 105, 83, 115, 157, 164, 149, 80, 92, 169, 86, 168, 135, 33, 181, 106, 104, 244, 31, 123, 194, 159, 69, 96, 185, 224, 199, 240, 126, 28]

[address_vp_types]
token = ["atest1v4ehgw36xdzryve5gsc52veeg5cnsv2yx5eygvp38qcrvd29xy6rys6p8yc5xvp4xfpy2v694wgwcp", "atest1v4ehgw36gfryydj9g3p5zv3kg9znyd358ycnzsfcggc5gvecgc6ygs2rxv6ry3zpg4zrwdfeumqcz9", "atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5", "atest1v4ehgw36gg6nvs2zgfpyxsfjgc65yv6pxy6nwwfsxgungdzrggeyzv35gveyxsjyxymyz335hur2jn", "atest1v4ehgw36xqmr2d3nx3ryvd2xxgmrq33j8qcns33sxezrgv6zxdzrydjrxveygd2yxumrsdpsf9jc2p", "atest1v4ehgw36gep5ysecxq6nyv3jg3zygv3e89qn2vp48pryxsf4xpznvve5gvmy23fs89pryvf5a6ht90", "atest1v4ehgw36xue5xvf5xvuyzvpjx5un2v3k8qeyvd3cxdqns32p89rrxd6xx9zngvpegccnzs699rdnnt"]
